CREATE SCHEMA IF NOT EXISTS palayan_inventor;

-- Create tables in palayan_inventor schema
CREATE TABLE IF NOT EXISTS palayan_inventor.items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sheet_name TEXT,
  article TEXT,
  description TEXT,
  property_number TEXT UNIQUE,
  quantity BIGINT,
  unit TEXT,
  unit_value DOUBLE PRECISION,
  total_value DOUBLE PRECISION,
  date_acquired TEXT,
  remarks TEXT,
  accountable_officer TEXT,
  status TEXT,
  raw_row TEXT
);

CREATE TABLE IF NOT EXISTS palayan_inventor.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE,
  password_hash TEXT,
  role TEXT,
  status TEXT DEFAULT 'approved'
);

CREATE TABLE IF NOT EXISTS palayan_inventor.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT,
  action TEXT,
  timestamp TEXT,
  details TEXT
);

CREATE TABLE IF NOT EXISTS palayan_inventor.sessions (
  sid TEXT PRIMARY KEY,
  sess TEXT,
  expire BIGINT
);

-- Create tables in public schema
CREATE TABLE IF NOT EXISTS public.items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sheet_name TEXT,
  article TEXT,
  description TEXT,
  property_number TEXT UNIQUE,
  quantity BIGINT,
  unit TEXT,
  unit_value DOUBLE PRECISION,
  total_value DOUBLE PRECISION,
  date_acquired TEXT,
  remarks TEXT,
  accountable_officer TEXT,
  status TEXT,
  raw_row TEXT
);

CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE,
  password_hash TEXT,
  role TEXT,
  status TEXT DEFAULT 'approved'
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT,
  action TEXT,
  timestamp TEXT,
  details TEXT
);

CREATE TABLE IF NOT EXISTS public.sessions (
  sid TEXT PRIMARY KEY,
  sess TEXT,
  expire BIGINT
);
